import type { skill } from '../schema/skill';

type NewSkill = typeof skill.$inferInsert;

export const SKILLS: NewSkill[] = [
    // agility
    { uid: crypto.randomUUID(), type: 'agility', name: 'reception' },
    { uid: crypto.randomUUID(), type: 'agility', name: 'reception plongeante' },
    { uid: crypto.randomUUID(), type: 'agility', name: 'tacle plongeant' },
    { uid: crypto.randomUUID(), type: 'agility', name: 'esquive' },
    { uid: crypto.randomUUID(), type: 'agility', name: 'defenseur' },
    { uid: crypto.randomUUID(), type: 'agility', name: 'frappe-et-court' },
    { uid: crypto.randomUUID(), type: 'agility', name: 'retablissement' },
    { uid: crypto.randomUUID(), type: 'agility', name: 'saut' },
    { uid: crypto.randomUUID(), type: 'agility', name: 'liberation controlee' },
    { uid: crypto.randomUUID(), type: 'agility', name: 'glissade controlee' },
    { uid: crypto.randomUUID(), type: 'agility', name: 'sprint' },
    { uid: crypto.randomUUID(), type: 'agility', name: 'equilibre' },
    // strength
    { uid: crypto.randomUUID(), type: 'strength', name: 'cle de bras' },
    { uid: crypto.randomUUID(), type: 'strength', name: 'bagarreur' },
    { uid: crypto.randomUUID(), type: 'strength', name: 'esquive en force' },
    { uid: crypto.randomUUID(), type: 'strength', name: 'dans le mille' },
    { uid: crypto.randomUUID(), type: 'strength', name: 'projection' },
    { uid: crypto.randomUUID(), type: 'strength', name: 'garde' },
    { uid: crypto.randomUUID(), type: 'strength', name: 'juggernaut' },
    { uid: crypto.randomUUID(), type: 'strength', name: 'chataigne' },
    { uid: crypto.randomUUID(), type: 'strength', name: 'blocage multiple' },
    { uid: crypto.randomUUID(), type: 'strength', name: 'stabilite' },
    { uid: crypto.randomUUID(), type: 'strength', name: 'bras muscle' },
    { uid: crypto.randomUUID(), type: 'strength', name: 'crane epais' },
    // general
    { uid: crypto.randomUUID(), type: 'general', name: 'blocage' },
    { uid: crypto.randomUUID(), type: 'general', name: 'intrepide' },
    { uid: crypto.randomUUID(), type: 'general', name: 'parade' },
    { uid: crypto.randomUUID(), type: 'general', name: 'frenesie' },
    { uid: crypto.randomUUID(), type: 'general', name: 'frappe precise' },
    { uid: crypto.randomUUID(), type: 'general', name: 'pro' },
    { uid: crypto.randomUUID(), type: 'general', name: 'appuis surs' },
    { uid: crypto.randomUUID(), type: 'general', name: 'arracher le ballon' },
    { uid: crypto.randomUUID(), type: 'general', name: 'prise sure' },
    { uid: crypto.randomUUID(), type: 'general', name: 'tacle' },
    { uid: crypto.randomUUID(), type: 'general', name: 'provocation' },
    { uid: crypto.randomUUID(), type: 'general', name: 'lutte' },
    // mutation
    { uid: crypto.randomUUID(), type: 'mutation', name: 'main demesuree' },
    { uid: crypto.randomUUID(), type: 'mutation', name: 'griffes' },
    { uid: crypto.randomUUID(), type: 'mutation', name: 'presence perturbante' },
    { uid: crypto.randomUUID(), type: 'mutation', name: 'bras supplementaires' },
    { uid: crypto.randomUUID(), type: 'mutation', name: 'repulsion' },
    { uid: crypto.randomUUID(), type: 'mutation', name: 'cornes' },
    { uid: crypto.randomUUID(), type: 'mutation', name: 'peau de fer' },
    { uid: crypto.randomUUID(), type: 'mutation', name: 'grande gueule' },
    { uid: crypto.randomUUID(), type: 'mutation', name: 'queue prehensible' },
    { uid: crypto.randomUUID(), type: 'mutation', name: 'tentacules' },
    { uid: crypto.randomUUID(), type: 'mutation', name: 'deux tetes' },
    { uid: crypto.randomUUID(), type: 'mutation', name: 'tres longues jambes' },
    // passing
    { uid: crypto.randomUUID(), type: 'passing', name: 'precision' },
    { uid: crypto.randomUUID(), type: 'passing', name: 'canonnier' },
    { uid: crypto.randomUUID(), type: 'passing', name: 'perce-nuages' },
    { uid: crypto.randomUUID(), type: 'passing', name: 'delestage' },
    { uid: crypto.randomUUID(), type: 'passing', name: 'transmission dans la course' },
    { uid: crypto.randomUUID(), type: 'passing', name: 'passe desesperee' },
    { uid: crypto.randomUUID(), type: 'passing', name: 'chef' },
    { uid: crypto.randomUUID(), type: 'passing', name: 'nerfs d\'acier' },
    { uid: crypto.randomUUID(), type: 'passing', name: 'sur le ballon' },
    { uid: crypto.randomUUID(), type: 'passing', name: 'passe' },
    { uid: crypto.randomUUID(), type: 'passing', name: 'desengagement' },
    { uid: crypto.randomUUID(), type: 'passing', name: 'passe assuree' },
    // devious
    { uid: crypto.randomUUID(), type: 'devious', name: 'joueur deloyal' },
    { uid: crypto.randomUUID(), type: 'devious', name: 'fourchette' },
    { uid: crypto.randomUUID(), type: 'devious', name: 'fumblerooski' },
    { uid: crypto.randomUUID(), type: 'devious', name: 'vol fatal' },
    { uid: crypto.randomUUID(), type: 'devious', name: 'agresseur solitaire' },
    { uid: crypto.randomUUID(), type: 'devious', name: 'marteau-pilon' },
    { uid: crypto.randomUUID(), type: 'devious', name: 'coup de crampons' },
    { uid: crypto.randomUUID(), type: 'devious', name: 'agression eclair' },
    { uid: crypto.randomUUID(), type: 'devious', name: 'saboteur' },
    { uid: crypto.randomUUID(), type: 'devious', name: 'poursuite' },
    { uid: crypto.randomUUID(), type: 'devious', name: 'sournois' },
    { uid: crypto.randomUUID(), type: 'devious', name: 'innovateur violent' },
    // traits
    { uid: crypto.randomUUID(), type: 'traits', name: 'animosite' },
    { uid: crypto.randomUUID(), type: 'traits', name: 'arme secrete' },
    { uid: crypto.randomUUID(), type: 'traits', name: 'bombardier' },
    { uid: crypto.randomUUID(), type: 'traits', name: 'botter de coequipier' },
    { uid: crypto.randomUUID(), type: 'traits', name: 'cerveau lent' },
    { uid: crypto.randomUUID(), type: 'traits', name: 'chaine et boulet' },
    { uid: crypto.randomUUID(), type: 'traits', name: 'contagieux' },
    { uid: crypto.randomUUID(), type: 'traits', name: 'decomposition' },
    { uid: crypto.randomUUID(), type: 'traits', name: 'farceur' },
    { uid: crypto.randomUUID(), type: 'traits', name: 'fureur debridee' },
    { uid: crypto.randomUUID(), type: 'traits', name: 'gerbe de vomi' },
    { uid: crypto.randomUUID(), type: 'traits', name: 'gros debile' },
    { uid: crypto.randomUUID(), type: 'traits', name: 'haine' },
    { uid: crypto.randomUUID(), type: 'traits', name: 'insignifiant' },
    { uid: crypto.randomUUID(), type: 'traits', name: 'instable' },
    { uid: crypto.randomUUID(), type: 'traits', name: 'ivrogne' },
    { uid: crypto.randomUUID(), type: 'traits', name: 'lancer de coequipier' },
    { uid: crypto.randomUUID(), type: 'traits', name: 'microbe' },
    { uid: crypto.randomUUID(), type: 'traits', name: 'minus' },
    { uid: crypto.randomUUID(), type: 'traits', name: 'mon ballon' },
    { uid: crypto.randomUUID(), type: 'traits', name: 'monte sur ressort' },
    { uid: crypto.randomUUID(), type: 'traits', name: 'petit remontant' },
    { uid: crypto.randomUUID(), type: 'traits', name: 'pique' },
    { uid: crypto.randomUUID(), type: 'traits', name: 'poids plume' },
    { uid: crypto.randomUUID(), type: 'traits', name: 'poignard' },
    { uid: crypto.randomUUID(), type: 'traits', name: 'prendre racine' },
    { uid: crypto.randomUUID(), type: 'traits', name: 'regard hypnotique' },
    { uid: crypto.randomUUID(), type: 'traits', name: 'regeneration' },
    { uid: crypto.randomUUID(), type: 'traits', name: 'sans ballon' },
    { uid: crypto.randomUUID(), type: 'traits', name: 'sauvagerie animale' },
    { uid: crypto.randomUUID(), type: 'traits', name: 'soif de sang(X+)' },
    { uid: crypto.randomUUID(), type: 'traits', name: 'solitaire(X+)' },
    { uid: crypto.randomUUID(), type: 'traits', name: 'souffle ardent' },
    { uid: crypto.randomUUID(), type: 'traits', name: 'timmm-ber!' },
    { uid: crypto.randomUUID(), type: 'traits', name: 'toujours affame' },
    { uid: crypto.randomUUID(), type: 'traits', name: 'tronconneuse' },
];
