import type { SkillRule } from '../schema/rules';

export const SKILLS: SkillRule[] = [
    // agility
    { uid: crypto.randomUUID(), type: 'agility', mandatory: false, name: 'réception' },
    { uid: crypto.randomUUID(), type: 'agility', mandatory: false, name: 'réception plongeante' },
    { uid: crypto.randomUUID(), type: 'agility', mandatory: false, name: 'tacle plongeant' },
    { uid: crypto.randomUUID(), type: 'agility', mandatory: false, name: 'esquive' },
    { uid: crypto.randomUUID(), type: 'agility', mandatory: false, name: 'défenseur' },
    { uid: crypto.randomUUID(), type: 'agility', mandatory: false, name: 'frappe-et-court' },
    { uid: crypto.randomUUID(), type: 'agility', mandatory: false, name: 'rétablissement' },
    { uid: crypto.randomUUID(), type: 'agility', mandatory: false, name: 'saut' },
    { uid: crypto.randomUUID(), type: 'agility', mandatory: false, name: 'libération contrôlée' },
    { uid: crypto.randomUUID(), type: 'agility', mandatory: false, name: 'glissade contrôlée' },
    { uid: crypto.randomUUID(), type: 'agility', mandatory: false, name: 'sprint' },
    { uid: crypto.randomUUID(), type: 'agility', mandatory: false, name: 'équilibre' },
    // strength
    { uid: crypto.randomUUID(), type: 'strength', mandatory: false, name: 'clé de bras' },
    { uid: crypto.randomUUID(), type: 'strength', mandatory: false, name: 'bagarreur' },
    { uid: crypto.randomUUID(), type: 'strength', mandatory: false, name: 'esquive en force' },
    { uid: crypto.randomUUID(), type: 'strength', mandatory: false, name: 'dans le mille' },
    { uid: crypto.randomUUID(), type: 'strength', mandatory: false, name: 'projection' },
    { uid: crypto.randomUUID(), type: 'strength', mandatory: false, name: 'garde' },
    { uid: crypto.randomUUID(), type: 'strength', mandatory: false, name: 'juggernaut' },
    { uid: crypto.randomUUID(), type: 'strength', mandatory: false, name: 'châtaigne' },
    { uid: crypto.randomUUID(), type: 'strength', mandatory: false, name: 'blocage multiple' },
    { uid: crypto.randomUUID(), type: 'strength', mandatory: false, name: 'stabilité' },
    { uid: crypto.randomUUID(), type: 'strength', mandatory: false, name: 'bras musclé' },
    { uid: crypto.randomUUID(), type: 'strength', mandatory: false, name: 'crâne épais' },
    // general
    { uid: crypto.randomUUID(), type: 'general', mandatory: false, name: 'blocage' },
    { uid: crypto.randomUUID(), type: 'general', mandatory: false, name: 'intrépide' },
    { uid: crypto.randomUUID(), type: 'general', mandatory: false, name: 'parade' },
    { uid: crypto.randomUUID(), type: 'general', mandatory: true, name: 'frénésie' },
    { uid: crypto.randomUUID(), type: 'general', mandatory: false, name: 'frappe précise' },
    { uid: crypto.randomUUID(), type: 'general', mandatory: false, name: 'pro' },
    { uid: crypto.randomUUID(), type: 'general', mandatory: false, name: 'appuis sûrs' },
    { uid: crypto.randomUUID(), type: 'general', mandatory: false, name: 'arracher le ballon' },
    { uid: crypto.randomUUID(), type: 'general', mandatory: false, name: 'prise sûre' },
    { uid: crypto.randomUUID(), type: 'general', mandatory: false, name: 'tacle' },
    { uid: crypto.randomUUID(), type: 'general', mandatory: false, name: 'provocation' },
    { uid: crypto.randomUUID(), type: 'general', mandatory: false, name: 'lutte' },
    // mutation
    { uid: crypto.randomUUID(), type: 'mutation', mandatory: false, name: 'main demesurée' },
    { uid: crypto.randomUUID(), type: 'mutation', mandatory: false, name: 'griffes' },
    { uid: crypto.randomUUID(), type: 'mutation', mandatory: true, name: 'présence perturbante' },
    { uid: crypto.randomUUID(), type: 'mutation', mandatory: false, name: 'bras supplémentaires' },
    { uid: crypto.randomUUID(), type: 'mutation', mandatory: true, name: 'répulsion' },
    { uid: crypto.randomUUID(), type: 'mutation', mandatory: false, name: 'cornes' },
    { uid: crypto.randomUUID(), type: 'mutation', mandatory: false, name: 'peau de fer' },
    { uid: crypto.randomUUID(), type: 'mutation', mandatory: false, name: 'grande gueule' },
    { uid: crypto.randomUUID(), type: 'mutation', mandatory: false, name: 'queue préhensible' },
    { uid: crypto.randomUUID(), type: 'mutation', mandatory: false, name: 'tentacules' },
    { uid: crypto.randomUUID(), type: 'mutation', mandatory: false, name: 'deux têtes' },
    { uid: crypto.randomUUID(), type: 'mutation', mandatory: false, name: 'très longues jambes' },
    // passing
    { uid: crypto.randomUUID(), type: 'passing', mandatory: false, name: 'précision' },
    { uid: crypto.randomUUID(), type: 'passing', mandatory: false, name: 'canonnier' },
    { uid: crypto.randomUUID(), type: 'passing', mandatory: false, name: 'perce-nuages' },
    { uid: crypto.randomUUID(), type: 'passing', mandatory: false, name: 'délestage' },
    { uid: crypto.randomUUID(), type: 'passing', mandatory: false, name: 'transmission dans la course' },
    { uid: crypto.randomUUID(), type: 'passing', mandatory: false, name: 'passe désespérée' },
    { uid: crypto.randomUUID(), type: 'passing', mandatory: false, name: 'chef' },
    { uid: crypto.randomUUID(), type: 'passing', mandatory: false, name: 'nerfs d\'acier' },
    { uid: crypto.randomUUID(), type: 'passing', mandatory: false, name: 'sur le ballon' },
    { uid: crypto.randomUUID(), type: 'passing', mandatory: false, name: 'passe' },
    { uid: crypto.randomUUID(), type: 'passing', mandatory: false, name: 'dégagement' },
    { uid: crypto.randomUUID(), type: 'passing', mandatory: false, name: 'passe assurée' },
    // devious
    { uid: crypto.randomUUID(), type: 'devious', mandatory: false, name: 'joueur déloyal' },
    { uid: crypto.randomUUID(), type: 'devious', mandatory: false, name: 'fourchette' },
    { uid: crypto.randomUUID(), type: 'devious', mandatory: false, name: 'fumblerooski' },
    { uid: crypto.randomUUID(), type: 'devious', mandatory: false, name: 'vol fatal' },
    { uid: crypto.randomUUID(), type: 'devious', mandatory: false, name: 'agresseur solitaire' },
    { uid: crypto.randomUUID(), type: 'devious', mandatory: false, name: 'marteau-pilon' },
    { uid: crypto.randomUUID(), type: 'devious', mandatory: false, name: 'coup de crampons' },
    { uid: crypto.randomUUID(), type: 'devious', mandatory: false, name: 'agression éclair' },
    { uid: crypto.randomUUID(), type: 'devious', mandatory: false, name: 'saboteur' },
    { uid: crypto.randomUUID(), type: 'devious', mandatory: false, name: 'poursuite' },
    { uid: crypto.randomUUID(), type: 'devious', mandatory: false, name: 'sournois' },
    { uid: crypto.randomUUID(), type: 'devious', mandatory: false, name: 'innovateur violent' },
    // traits
    { uid: crypto.randomUUID(), type: 'traits', mandatory: true, name: 'animosité (X)' },
    { uid: crypto.randomUUID(), type: 'traits', mandatory: true, name: 'arme secrète' },
    { uid: crypto.randomUUID(), type: 'traits', mandatory: false, name: 'bombardier' },
    { uid: crypto.randomUUID(), type: 'traits', mandatory: false, name: 'botter de coéquipier' },
    { uid: crypto.randomUUID(), type: 'traits', mandatory: true, name: 'cerveau lent' },
    { uid: crypto.randomUUID(), type: 'traits', mandatory: true, name: 'chaîne et boulet' },
    { uid: crypto.randomUUID(), type: 'traits', mandatory: false, name: 'contagieux' },
    { uid: crypto.randomUUID(), type: 'traits', mandatory: true, name: 'décomposition' },
    { uid: crypto.randomUUID(), type: 'traits', mandatory: false, name: 'farceur' },
    { uid: crypto.randomUUID(), type: 'traits', mandatory: true, name: 'fureur débridée' },
    { uid: crypto.randomUUID(), type: 'traits', mandatory: false, name: 'gerbe de vomi' },
    { uid: crypto.randomUUID(), type: 'traits', mandatory: true, name: 'gros débile' },
    { uid: crypto.randomUUID(), type: 'traits', mandatory: true, name: 'haine (X)' },
    { uid: crypto.randomUUID(), type: 'traits', mandatory: true, name: 'insignifiant' },
    { uid: crypto.randomUUID(), type: 'traits', mandatory: true, name: 'instable' },
    { uid: crypto.randomUUID(), type: 'traits', mandatory: true, name: 'ivrogne' },
    { uid: crypto.randomUUID(), type: 'traits', mandatory: false, name: 'lancer de coéquipier' },
    { uid: crypto.randomUUID(), type: 'traits', mandatory: true, name: 'microbe' },
    { uid: crypto.randomUUID(), type: 'traits', mandatory: true, name: 'minus' },
    { uid: crypto.randomUUID(), type: 'traits', mandatory: true, name: 'mon ballon' },
    { uid: crypto.randomUUID(), type: 'traits', mandatory: false, name: 'monté sur ressort' },
    { uid: crypto.randomUUID(), type: 'traits', mandatory: false, name: 'petit remontant' },
    { uid: crypto.randomUUID(), type: 'traits', mandatory: false, name: 'piqué' },
    { uid: crypto.randomUUID(), type: 'traits', mandatory: true, name: 'poids plume' },
    { uid: crypto.randomUUID(), type: 'traits', mandatory: false, name: 'poignard' },
    { uid: crypto.randomUUID(), type: 'traits', mandatory: true, name: 'prendre racine' },
    { uid: crypto.randomUUID(), type: 'traits', mandatory: false, name: 'regard hypnotique' },
    { uid: crypto.randomUUID(), type: 'traits', mandatory: false, name: 'régénération' },
    { uid: crypto.randomUUID(), type: 'traits', mandatory: true, name: 'sans ballon' },
    { uid: crypto.randomUUID(), type: 'traits', mandatory: true, name: 'sauvagerie animale' },
    { uid: crypto.randomUUID(), type: 'traits', mandatory: true, name: 'soif de sang (X+)' },
    { uid: crypto.randomUUID(), type: 'traits', mandatory: true, name: 'solitaire (X+)' },
    { uid: crypto.randomUUID(), type: 'traits', mandatory: false, name: 'souffle ardent' },
    { uid: crypto.randomUUID(), type: 'traits', mandatory: false, name: 'timmm-ber!' },
    { uid: crypto.randomUUID(), type: 'traits', mandatory: true, name: 'toujours affamé' },
    { uid: crypto.randomUUID(), type: 'traits', mandatory: true, name: 'tronçonneuse' },
];
