export const TEAMS = [
    { uid: crypto.randomUUID(), reroll_cost: 60000, apothecary: true, name: 'amazones' },
    { uid: crypto.randomUUID(), reroll_cost: 60000, apothecary: true, name: 'orques noirs' },
    { uid: crypto.randomUUID(), reroll_cost: 60000, apothecary: true, name: 'bretonniens' },
    { uid: crypto.randomUUID(), reroll_cost: 50000, apothecary: true, name: 'Elus du chaos' },
    { uid: crypto.randomUUID(), reroll_cost: 70000, apothecary: true, name: 'Nain du chaos' },
    { uid: crypto.randomUUID(), reroll_cost: 70000, apothecary: true, name: 'Renegats du chaos' },
    { uid: crypto.randomUUID(), reroll_cost: 50000, apothecary: true, name: 'elfes noirs' },
    { uid: crypto.randomUUID(), reroll_cost: 60000, apothecary: true, name: 'nains' },
    { uid: crypto.randomUUID(), reroll_cost: 50000, apothecary: true, name: 'union elfique' },
    { uid: crypto.randomUUID(), reroll_cost: 50000, apothecary: true, name: 'gnomes' },
    { uid: crypto.randomUUID(), reroll_cost: 60000, apothecary: true, name: 'gobelins' },
    { uid: crypto.randomUUID(), reroll_cost: 60000, apothecary: true, name: 'halfings' },
    { uid: crypto.randomUUID(), reroll_cost: 50000, apothecary: true, name: 'humains' },
    { uid: crypto.randomUUID(), reroll_cost: 60000, apothecary: true, name: 'noblesse imperiale' },
    { uid: crypto.randomUUID(), reroll_cost: 60000, apothecary: true, name: 'khorne' },
    { uid: crypto.randomUUID(), reroll_cost: 70000, apothecary: true, name: 'hommes-lezards' },
    { uid: crypto.randomUUID(), reroll_cost: 70000, apothecary: false, name: 'horreurs necromantiques' },
    { uid: crypto.randomUUID(), reroll_cost: 60000, apothecary: true, name: 'nordiques' },
    { uid: crypto.randomUUID(), reroll_cost: 60000, apothecary: false, name: 'nurgle' },
    { uid: crypto.randomUUID(), reroll_cost: 70000, apothecary: true, name: 'ogres' },
    { uid: crypto.randomUUID(), reroll_cost: 70000, apothecary: true, name: 'alliance du vieux monde' },
    { uid: crypto.randomUUID(), reroll_cost: 60000, apothecary: true, name: 'orques' },
    { uid: crypto.randomUUID(), reroll_cost: 70000, apothecary: false, name: 'morts ambulants' },
    { uid: crypto.randomUUID(), reroll_cost: 50000, apothecary: true, name: 'skavens' },
    { uid: crypto.randomUUID(), reroll_cost: 70000, apothecary: true, name: 'snotlings' },
    { uid: crypto.randomUUID(), reroll_cost: 60000, apothecary: false, name: 'rois des tombes' },
    { uid: crypto.randomUUID(), reroll_cost: 70000, apothecary: true, name: 'bas-fonds' },
    { uid: crypto.randomUUID(), reroll_cost: 60000, apothecary: true, name: 'vampires' },
    { uid: crypto.randomUUID(), reroll_cost: 50000, apothecary: true, name: 'elfes sylvains' },
];
